#!/usr/bin/env bash
set -ex
python make_dataset.py class1_input.dat class1 class1_input.dat.pkl.gz
python run_deepneo.py class1 mhc class1_input.dat.pkl.gz class1_mhcbinding_result.txt
python run_deepneo.py class1 tcr class1_input.dat.pkl.gz class1_immunogenicity_result.txt
